[package]
name = "trends"
version = "0.1.1"
edition = "2024"
readme="README.md"
authors=["oOp","Ossama.abboud95@gmail.com"]
keywords = ["trend", "comparison", "ordering", "utility", "ord"]
categories = ["algorithms", "rust-patterns"]
description = "Simple trend detection for ordered values"
license = "MIT"
repository="https://github.com/oOp995/trends"

[dependencies]
